version: '3.8'
services:
  web:
    image: web
    depends_on:
      - api
    container_name: "${COMPOSE_PROJECT_NAME}-web-service"
    environment:
      - apiPath=http://api:3333
    ports:
      - '3000:3000'
  api:
    image: api
    container_name: "${COMPOSE_PROJECT_NAME}-api-service"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3333:3333'
  db:
    image: mongo
    container_name: "${COMPOSE_PROJECT_NAME}-db-service"
    restart: unless-stopped
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017


